/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgRouteImport } from './routes/$org'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authUnauthorizedRouteImport } from './routes/(auth)/unauthorized'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authAcceptInvitationRouteImport } from './routes/(auth)/accept-invitation'
import { Route as OrgUsersRouteImport } from './routes/$org/users'
import { Route as OrgSitesRouteImport } from './routes/$org/sites'
import { Route as OrgDashboardRouteImport } from './routes/$org/dashboard'

const OrgRoute = OrgRouteImport.update({
  id: '/$org',
  path: '/$org',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authUnauthorizedRoute = authUnauthorizedRouteImport.update({
  id: '/(auth)/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authAcceptInvitationRoute = authAcceptInvitationRouteImport.update({
  id: '/(auth)/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgUsersRoute = OrgUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => OrgRoute,
} as any)
const OrgSitesRoute = OrgSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => OrgRoute,
} as any)
const OrgDashboardRoute = OrgDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OrgRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$org': typeof OrgRouteWithChildren
  '/$org/dashboard': typeof OrgDashboardRoute
  '/$org/sites': typeof OrgSitesRoute
  '/$org/users': typeof OrgUsersRoute
  '/accept-invitation': typeof authAcceptInvitationRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/unauthorized': typeof authUnauthorizedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$org': typeof OrgRouteWithChildren
  '/$org/dashboard': typeof OrgDashboardRoute
  '/$org/sites': typeof OrgSitesRoute
  '/$org/users': typeof OrgUsersRoute
  '/accept-invitation': typeof authAcceptInvitationRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/unauthorized': typeof authUnauthorizedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$org': typeof OrgRouteWithChildren
  '/$org/dashboard': typeof OrgDashboardRoute
  '/$org/sites': typeof OrgSitesRoute
  '/$org/users': typeof OrgUsersRoute
  '/(auth)/accept-invitation': typeof authAcceptInvitationRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/unauthorized': typeof authUnauthorizedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$org'
    | '/$org/dashboard'
    | '/$org/sites'
    | '/$org/users'
    | '/accept-invitation'
    | '/login'
    | '/register'
    | '/unauthorized'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$org'
    | '/$org/dashboard'
    | '/$org/sites'
    | '/$org/users'
    | '/accept-invitation'
    | '/login'
    | '/register'
    | '/unauthorized'
  id:
    | '__root__'
    | '/'
    | '/$org'
    | '/$org/dashboard'
    | '/$org/sites'
    | '/$org/users'
    | '/(auth)/accept-invitation'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/unauthorized'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgRoute: typeof OrgRouteWithChildren
  authAcceptInvitationRoute: typeof authAcceptInvitationRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authUnauthorizedRoute: typeof authUnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$org': {
      id: '/$org'
      path: '/$org'
      fullPath: '/$org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/unauthorized': {
      id: '/(auth)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof authUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/accept-invitation': {
      id: '/(auth)/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof authAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$org/users': {
      id: '/$org/users'
      path: '/users'
      fullPath: '/$org/users'
      preLoaderRoute: typeof OrgUsersRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/sites': {
      id: '/$org/sites'
      path: '/sites'
      fullPath: '/$org/sites'
      preLoaderRoute: typeof OrgSitesRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/dashboard': {
      id: '/$org/dashboard'
      path: '/dashboard'
      fullPath: '/$org/dashboard'
      preLoaderRoute: typeof OrgDashboardRouteImport
      parentRoute: typeof OrgRoute
    }
  }
}

interface OrgRouteChildren {
  OrgDashboardRoute: typeof OrgDashboardRoute
  OrgSitesRoute: typeof OrgSitesRoute
  OrgUsersRoute: typeof OrgUsersRoute
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgDashboardRoute: OrgDashboardRoute,
  OrgSitesRoute: OrgSitesRoute,
  OrgUsersRoute: OrgUsersRoute,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgRoute: OrgRouteWithChildren,
  authAcceptInvitationRoute: authAcceptInvitationRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authUnauthorizedRoute: authUnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
