export declare const ACCEPTED = 202;
export declare const BAD_GATEWAY = 502;
export declare const BAD_REQUEST = 400;
export declare const CONFLICT = 409;
export declare const CONTINUE = 100;
export declare const CREATED = 201;
export declare const EXPECTATION_FAILED = 417;
export declare const FAILED_DEPENDENCY = 424;
export declare const FORBIDDEN = 403;
export declare const GATEWAY_TIMEOUT = 504;
export declare const GONE = 410;
export declare const HTTP_VERSION_NOT_SUPPORTED = 505;
export declare const IM_A_TEAPOT = 418;
export declare const INSUFFICIENT_SPACE_ON_RESOURCE = 419;
export declare const INSUFFICIENT_STORAGE = 507;
export declare const INTERNAL_SERVER_ERROR = 500;
export declare const LENGTH_REQUIRED = 411;
export declare const LOCKED = 423;
export declare const METHOD_FAILURE = 420;
export declare const METHOD_NOT_ALLOWED = 405;
export declare const MOVED_PERMANENTLY = 301;
export declare const MOVED_TEMPORARILY = 302;
export declare const MULTI_STATUS = 207;
export declare const MULTIPLE_CHOICES = 300;
export declare const NETWORK_AUTHENTICATION_REQUIRED = 511;
export declare const NO_CONTENT = 204;
export declare const NON_AUTHORITATIVE_INFORMATION = 203;
export declare const NOT_ACCEPTABLE = 406;
export declare const NOT_FOUND = 404;
export declare const NOT_IMPLEMENTED = 501;
export declare const NOT_MODIFIED = 304;
export declare const OK = 200;
export declare const PARTIAL_CONTENT = 206;
export declare const PAYMENT_REQUIRED = 402;
export declare const PERMANENT_REDIRECT = 308;
export declare const PRECONDITION_FAILED = 412;
export declare const PRECONDITION_REQUIRED = 428;
export declare const PROCESSING = 102;
export declare const EARLY_HINTS = 103;
export declare const UPGRADE_REQUIRED = 426;
export declare const PROXY_AUTHENTICATION_REQUIRED = 407;
export declare const REQUEST_HEADER_FIELDS_TOO_LARGE = 431;
export declare const REQUEST_TIMEOUT = 408;
export declare const REQUEST_TOO_LONG = 413;
export declare const REQUEST_URI_TOO_LONG = 414;
export declare const REQUESTED_RANGE_NOT_SATISFIABLE = 416;
export declare const RESET_CONTENT = 205;
export declare const SEE_OTHER = 303;
export declare const SERVICE_UNAVAILABLE = 503;
export declare const SWITCHING_PROTOCOLS = 101;
export declare const TEMPORARY_REDIRECT = 307;
export declare const TOO_MANY_REQUESTS = 429;
export declare const UNAUTHORIZED = 401;
export declare const UNAVAILABLE_FOR_LEGAL_REASONS = 451;
export declare const UNPROCESSABLE_ENTITY = 422;
export declare const UNSUPPORTED_MEDIA_TYPE = 415;
export declare const USE_PROXY = 305;
export declare const MISDIRECTED_REQUEST = 421;
export declare const HttpStatusCode: {
    readonly ACCEPTED: 202;
    readonly BAD_GATEWAY: 502;
    readonly BAD_REQUEST: 400;
    readonly CONFLICT: 409;
    readonly CONTINUE: 100;
    readonly CREATED: 201;
    readonly EXPECTATION_FAILED: 417;
    readonly FAILED_DEPENDENCY: 424;
    readonly FORBIDDEN: 403;
    readonly GATEWAY_TIMEOUT: 504;
    readonly GONE: 410;
    readonly HTTP_VERSION_NOT_SUPPORTED: 505;
    readonly IM_A_TEAPOT: 418;
    readonly INSUFFICIENT_SPACE_ON_RESOURCE: 419;
    readonly INSUFFICIENT_STORAGE: 507;
    readonly INTERNAL_SERVER_ERROR: 500;
    readonly LENGTH_REQUIRED: 411;
    readonly LOCKED: 423;
    readonly METHOD_FAILURE: 420;
    readonly METHOD_NOT_ALLOWED: 405;
    readonly MOVED_PERMANENTLY: 301;
    readonly MOVED_TEMPORARILY: 302;
    readonly MULTI_STATUS: 207;
    readonly MULTIPLE_CHOICES: 300;
    readonly NETWORK_AUTHENTICATION_REQUIRED: 511;
    readonly NO_CONTENT: 204;
    readonly NON_AUTHORITATIVE_INFORMATION: 203;
    readonly NOT_ACCEPTABLE: 406;
    readonly NOT_FOUND: 404;
    readonly NOT_IMPLEMENTED: 501;
    readonly NOT_MODIFIED: 304;
    readonly OK: 200;
    readonly PARTIAL_CONTENT: 206;
    readonly PAYMENT_REQUIRED: 402;
    readonly PERMANENT_REDIRECT: 308;
    readonly PRECONDITION_FAILED: 412;
    readonly PRECONDITION_REQUIRED: 428;
    readonly PROCESSING: 102;
    readonly EARLY_HINTS: 103;
    readonly UPGRADE_REQUIRED: 426;
    readonly PROXY_AUTHENTICATION_REQUIRED: 407;
    readonly REQUEST_HEADER_FIELDS_TOO_LARGE: 431;
    readonly REQUEST_TIMEOUT: 408;
    readonly REQUEST_TOO_LONG: 413;
    readonly REQUEST_URI_TOO_LONG: 414;
    readonly REQUESTED_RANGE_NOT_SATISFIABLE: 416;
    readonly RESET_CONTENT: 205;
    readonly SEE_OTHER: 303;
    readonly SERVICE_UNAVAILABLE: 503;
    readonly SWITCHING_PROTOCOLS: 101;
    readonly TEMPORARY_REDIRECT: 307;
    readonly TOO_MANY_REQUESTS: 429;
    readonly UNAUTHORIZED: 401;
    readonly UNAVAILABLE_FOR_LEGAL_REASONS: 451;
    readonly UNPROCESSABLE_ENTITY: 422;
    readonly UNSUPPORTED_MEDIA_TYPE: 415;
    readonly USE_PROXY: 305;
    readonly MISDIRECTED_REQUEST: 421;
};
